apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: harshanamj/springboot-app
    newTag: dev-975a422
patches:
  - path: patch-dev.yaml        # deployment patch
  # - path: patch-svc-dev.yaml    # service patch