apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: harshanamj/springboot-app
    newTag: dev-4f3bb24
patches:
  - path: patch-dev.yaml        # deployment patch
  - path: ingress-patch.yaml     # ingress patch
  - path: patch-svc-dev.yaml    # service patch