apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../base
images:
  - name: harshanamj/springboot-app
    newTag: qa-c05f89f
patches:
  - path: patch-qa.yaml