apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../base
images:
  - name: harshanamj/springboot-app
    newTag: qa-5d7d53e
patches:
  - path: patch-qa.yaml
  - path: ingress-patch.yaml
  - path: patch-svc-qa.yaml
