apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../base
images:
  - name: harshanamj/springboot-app
    newTag: qa-a6f2cc9    
patches:
  - path: patch-qa.yaml
  - path: patch-svc-qa.yaml
