apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
images:
  - name: harshanamj/springboot-app
    newTag: main-df6883a
patches:
  - path: patch-prod.yaml        # deployment patch
  - path: patch-svc-prod.yaml    # service patch